---
prepare:
  fetch:
  - url: "https://raw.githubusercontent.com/voxable-labs/ruby-style-guide/master/.rubocop.yml"
    path: "rubocop-code-climate.yml"
engines:
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
    config:
      file: "rubocop-code-climate.yml"
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
ratings:
  paths:
  - "**.rb"
exclude_paths:
- spec/
